#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

nexus_ver=3.21.1-01

# Configuring image specific packages
echo "* Configuring image specific packages.";
#wget http://download.sonatype.com/nexus/3/nexus-${nexus_ver}-unix.tar.gz -O /root/nexus-${nexus_ver}-unix.tar.gz
wget http://mirrors.itime.biz/nexus/nexus-${nexus_ver}-unix.tar.gz -O /root/nexus-${nexus_ver}-unix.tar.gz
gtar xzf /root/nexus-${nexus_ver}-unix.tar.gz -C /opt

# data_dir
datadir=/nexus-data
# link nexus
ln -s /opt/nexus-${nexus_ver} /opt/nexus
# replace data_dir
sed -i '' "s|\.\./sonatype-work/nexus3|${datadir}|" /opt/nexus/bin/nexus.vmoptions

/usr/sbin/groupadd -g 200 nexus
/usr/sbin/useradd -u 200 -g nexus -d /opt/nexus -s /usr/bin/bash nexus

svccfg import /root/nexus.xml

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
